[package]
name = "distodon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
config = "0.13.3"
log = "0.4.17"
pretty_env_logger = "0.4.0"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.149", features = ["derive"] }
serde-aux = "4.1.2"
url = { version = "2.3.1", features = ["serde"] }
